name: publish

on:
  push:
    branches:
      - main


jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Environment setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: poetry setup
        run: |
          set -e && set -x
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m poetry config pypi-token.pypi $PYPI_TOKEN
          set -e
          python -m poetry publish --build
